Fix build with glibc 2.42
With the recent glibc update, the archaic `termio` ioctl interface was removed
from the API. Given that libsanitizer contained references to that API, the
build would break.

```
../../../../libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp:489:31:
error: invalid application of ‘sizeof’ to incomplete type ‘__sanitizer::termio’
```

See also
https://gcc.gnu.org/pipermail/gcc-patches/2025-May/682478.html